name: CICD

on:
  workflow_dispatch:


jobs:

  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "Checkout"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo "Building image"


  test:
    runs-on: ubuntu-latest
    steps:
      - name: testing
        run: echo "Testing"


  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run: echo "Code Deployed"




        
